server:
  port: 80
  access-log-enabled: true
logging:
  level:
    com.alibaba.druid: debug
    cn.gkate.estore.dao: debug
    org.springframework: WARN
  file: log\myspringboot.log
spring:
  messages:
    #国际化资源文件路径
      basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
      encoding.charset: UTF-8
      encoding.enable: true
      encoding.force: true
#      multipart:
#        enabled: false
#        max-file-size: 10MB(这里是限制的文件大小)
#        max-request-size: 10MB(这里是限制的文件大小)
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estoresystem?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties:
      config:
        decrypt: true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJSqdVCVg5KCyFyMW9FY1UtMniXa1VepoVEnQTthZyObHaKCqK3gelMeMavT8f8+D4mn1Fu18uA8TSx18/D03y8CAwEAAQ==
    useGlobalDataSourceStat: true
    druid:
      aop-patterns: com.gkate.estore.service.*
#      stat-view-servlet:  
#        login-username: admin
#        login-password: admin
  mail:
    host: smtp.163.com
    username: geomon
    password: lzs163
  aop:
    proxy-target-class: true
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: classpath:mybatis/
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/*/*Mapper.xml
  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml
